### ISSUE TITLE
My DS2 Pad Tests

### ISSUE THREAD

**Issue by venice1200** [vossstef/A2600Nano#25]
Hi @vossstef,
I build my DS2 Adapter for the Spare Pin Header of the MiSTeryNano Midi Shield today and did some tests with a modified Core v1.5 to be able to use the Spare Header Pins.

![IMG_1556_kl](https://github.com/user-attachments/assets/172d53a6-cfe6-4905-8b45-33dbd92de4c1)

```
Adapter for Spare Pin Header J8 (SPH) on the MiSTeryNano Shield and the Playstation Dualshock 2 Controller

Playstation Connector Pinout
 _____________
 |987 654 321|
 \___________/

Spare Pin Header Location and Pinout

       USB-C   
      |     |  ------
      |  T  |  |7531| <= SPH
Sub-D |  A  |  |8642|
      |  N  |  ------
      |  G  |
      |     |  2x MIDI
      |     |
       HDMI
	   
Adapter Connection
PS/DS Pin - SPH Pin (FPGA Pin) 
-----------------------------------------
  DAT   1 - 3 (P77)   MISO 
  CMD   2 - 2 (P74)   MOSI
        3 - nc        Rumble Voltage
        4 - 6         GND
        5 - 7         VCC/3,3v
  ATN   6 - 4 (P31)   CS
  CLK   7 - 1 (P73)   MCLK
  IRQ   8 - nc
  ACK   9 - nc

nc = not connected
```
Here are my Findings using the DS2 with my Adapter.

**DS2 Pad Analog Mode (LED) On or Off (doesn't matter)**
Testing with [H.E.R.O two Button Version](https://forums.atariage.com/topic/158430-rom-hacks-to-support-2-buttons-with-genesis-controllers/page/7/#comment-3118935) (NTSC)
Direction Buttons OK
Left Analog Stick **not working**
Select & Start Ok
Circle/A   = Button 1 (HERO Fire)
Cross/B   = **Right Direction (!)** 
             After pressing the Button the Direction Buttons are no longer working **(Paddle Mode?)**
             I need to press Circle/A to get the Direction Buttons working again
Traingle/X = **Left Direction (!)** 
             After pressing the Button the Direction Buttons are no longer working **(Paddle Mode?)**
             I need to press Circle/A to get the Direction Buttons working again
Square/Y   = Button 2 (HERO Bomb)
Shoulder Buttons no function
Same with HERO (OneButton) PAL Version 

**DS2 Pad Analog Mode On**
Testing Super Breakout 
Select & Start Ok
Slider Game Direction with Left Analog Stick (Left/Right) Ok
Circle/A  = After pressing the Button the left Analog Stick is no longer working
            I need to press Cross/B or Triangle/X or Square/Y to get the left Analog Stick working again
Cross/B  = Button 1 (Start Ball)
Triangle/X = no function
Square/Y = no function

Testing Video Olympics
Game Direction with Left Analog Stick (Up/Down) Ok
Need to invert Paddle direction

If you press the wrong button the Pad stops responding which is inconvenient (the same happens with an USB Pad).
Maybe a two button combination will be better for paddle activation/deactivation.

The first Button is Circle in Joystick Mode and Cross in Paddle Mode?

Btw, Mouse 🖱️ as Paddle works fine 👍 

Happy X-Mas 🎄

**Comment by vossstef** [comment]
@venice1200,
if you don't mind would like to add your cable build instructions incl picture for other users. Is that o.k ? 

Many thanks for your valuable feedback and would like to improve the design over the next weeks. 

I pretty much copied the mister core but let certain input switchmode function (joy, paddle, mouse) for the time being away and of course the key mapping might be different... 

Feel free to have a look at the readme.md  https://github.com/MiSTer-devel/Atari2600_MiSTer 
and https://github.com/MiSTer-devel/Atari7800_MiSTer to understand what i ported and about game control.

Initially i thought that porting of that small core is simple but ended up with a rather long lasting exhausting excersise and A7800  ROM autodetect and the video stabilizer blocks finally made the core working. Game Input  control was right from the beginning a nightmare...

**Comment by venice1200** [comment]
I am happy to help.

You can use anything I post for the documentation.

I used your code and added some modified files for supporting the Spare Pin Header for DS2.
If you like I can fork your repo, add my changes and send a pull request.

Nothing of the original work is changed.

**Comment by vossstef** [comment]
Hi @venice1200, 
i need to include the Shield Board pinheader as a selectable game input option in all the designs. Meaning present 'Joystick to DIP' in use and alternatively Shield pinheader for DS2. Would be great if you could create an extra jumper cable build instruction page (.md and graphics as .svg inkscape) with all needed deatils how to construct and purchase the needed parts. Also an edited TN20k drawing where new pinheader signals are shows will help too. Pls. list the new pins in your .cst file. I was yesterday evening browsing aliexpress to find your jumper cable but didn't found exact match but many parts that could be re-used to construct such a thing.

**Comment by venice1200** [comment]
Let me see what I can do for you.

I use an old (and maybe defective) Playstation Controller extension cable.
I was in luck as the female connector and the connected part of the cable was Ok.

I crimped the Pins onto the cables. Beta test Ok.

But I am waiting for female connector parts from Ali and I am going to create a PCB for this connector with a 10 Pin header to use 10-Pin flat cables and connectors for an easy 1:1 connection to the Pin Header of the MiSTery Nano Board.

I will provide my cst later.

Aloha

**Comment by vossstef** [comment]
.cst will use to update OSD and core that you immediately have a new input selection apart from further needed finetuning in the controller keymaps. 
Big Thanks !

**Comment by venice1200** [comment]
.cst attached.

[a2600_top_tn20k_ds2sph.zip](https://github.com/user-attachments/files/18222922/a2600_top_tn20k_ds2sph.zip)

**Comment by venice1200** [comment]
First Version...
![grafik](https://github.com/user-attachments/assets/6250e727-a336-4434-babe-73e633a8e7d4)

**Comment by vossstef** [comment]
Hi @venice1200 ,
PCB looks Great !

You will find the design changes here: https://github.com/vossstef/A2600Nano/tree/ds2_4_misteryboard20k
Pls. select in existing OSD "DS2 #2 Joy" as input port for the pinheader. I didn't tested as i don't have a cable yet but ordered a Y-Adapter from Ali that i could disintegrate.

**Comment by venice1200** [comment]
That works. 
With DS2 #2 i get the DS2 Pad working in the same way as my previuos test above.

> Hi @venice1200 , PCB looks Great !
> 
> You will find the design changes here: https://github.com/vossstef/A2600Nano/tree/ds2_4_misteryboard20k Pls. select in existing OSD "DS2 #2 Joy" as input port for the pinheader. I didn't tested as i don't have a cable yet but ordered a Y-Adapter from Ali that i could disintegrate.

If the femal connectors arrive I will double check the PCB and order some of them.

**Comment by venice1200** [comment]
Btw, is is now possible to use two DS2 Controller with the MiSTery Board?

No.1 using the original Pins
No.2 using the Spare Header

**Comment by vossstef** [comment]
> Btw, is is now possible to use two DS2 Controller with the MiSTery Board?
> 
> No.1 using the original Pins No.2 using the Spare Header

Yes both interfaces can be active at the same time. There is for the Joy to DIP interface no header but you could solder adhoc somw wires. Good point and i will meantion that in the readme too. Thought that coud could add via pull an extra document with the build instructions linked from readme.

**Comment by vossstef** [comment]
i merged the changes and cable doc to be added via pull

**Comment by venice1200** [comment]
Ok!
I will add pictures to „.assets“, correct?

**Comment by vossstef** [comment]
@venice1200 , yes pictures to .assets.
Will have a look into that and experimenting with strict setting in input control for Joy and Paddle mode.

**Comment by venice1200** [comment]
First Adapter Version Site
https://github.com/venice1200/A2600Nano/blob/main/shield_ds_cable.md

I am happy to send the pull request

Happy X-Mas

**Comment by vossstef** [comment]
Just send MR!
Looks great !!!

Also a Happy X-Mas :grinning:

**Comment by vossstef** [comment]
@venice1200 merge done and i have a small X-Mas gift for you :grinning:

I implemented a strict input selection for digital Joystick and Paddle. Hope that all your points are fixed now. 
https://github.com/vossstef/A2600Nano/tree/strict_input

In the root you will find an changed XML file for OSD control that have to be copied to the sdcard.

Pls. let me know...

and now it's finally X-Max :sparkles:

**Comment by venice1200** [comment]
>...Btw. my DS2 device behaves that left stick and Dpad are both simultaniously active at the same time.

Using which Version of the Core? 
With v1.2 to v1.4 I got the left stick only working in paddle mode.

>In the root you will find an changed XML file for OSD control 

The atari2600.xml file? 
Is this something I had to copy also for the older Version?

Many Thx

**Comment by vossstef** [comment]
@venice1200 You have to copy the .XML file to your sd card. i stored  a changed copy in the branch. pls. recompile the tn20k project in the branch and Flash to your tn20k.

**Comment by venice1200** [comment]
I copied the atari2600.xml file to the SD Card and compiled the "strict" Code using the 1.9.10 Education Version.
Using the 2 Buttton 60Hz Version of HERO again for testing two buttons.
Set Pad 1 to "DS2 #2 Joyst" Controller.
The Pad **is not set** to analog mode.
I start the game with F11 or Start at thew PAD.
Ledt stick not working at all.
Immediatly I press left or right to start the movment of HERO and the figure touch's the ground 
a bomp is dropped without any button presses!
Circle works as Trigger #1 (Laser)

The 1 Button PAL HERO Version works as expected.

Super Breakout PAL
Set Pad 1 to "DS2 #2 Paddl" Controller.
I start the game with F11 or Start at thew PAD.
The Pad **is set** to analog mode.
Ball release with Cross but no Paddle Movement with Left Stick.

Amybe I should try a version compiled by you.

**Comment by venice1200** [comment]
I use an Playstation Dualshock Controller SCPH-10010.
Tested two devices with the same type and the same result.

**Comment by vossstef** [comment]
> I use an Playstation Dualshock Controller SCPH-10010.
> Tested two devices with the same type and the same result.


i only have two different clones and they behave like that the stick is at the same time active  than  Dpad. Will try to find info about your model over the next days.

**Comment by venice1200** [comment]
Oh, if Iuse my USB Pad (Logitech Rumblepad 2) I have the same issue running the 2 Button Hero Version.
A bomb is dropped after the figure drops the ground.

**Comment by vossstef** [comment]
@venice1200 i am working for some while on a DS configuration command to switch in between digital and analog mode. This work is not finished yet. I need to understand the documentation further. Both to me known controller interface blocks just read and don't support device configuration methods. 

The 2nd Button topic (didn't know of 2nd button support at all) i should be able to fix over the next few days.

**Comment by venice1200** [comment]
Again my question if I should send you one of my Sony Controllers for testing?

And an Idea, could you add difficulty a/b to a keyboard button?

**Comment by vossstef** [comment]
core behaviour related to "2nd hacked trigger" button is almst clear to me and could be very likely be added (similar than C64 GS two button mode but differnet polarity)
i think more burning topic is why your original DS2 controller behaves differently than cheap clone types... I will need some time to diguest and understand.

**Comment by venice1200** [comment]
> core behaviour related to "2nd hacked trigger" button is almst clear to me and could be very likely be added

Maybe I was not precise enough, but the 2nd Button was already working for me using the DS2 Controller and the USB Pad with the version before the "strict" branch.

If you like me to send my DS2 controller let me know.

**Comment by vossstef** [comment]
@venice1200 pls. let me have a look at the 2nd button topic and then will move on with the DS2 configuration commands implementation. Maybe Stick and Dpad can be active at the same time if a certain config command send to the controller.
I don't need a original DS2 controller yet and will let you know if there is something to test. Need some time...

**Comment by vossstef** [comment]
@venice1200 i think 2nd fire button should work now for digital mode. Tested the HERO game with 2nd button hack.
I fixed also analog buttons.
https://github.com/vossstef/A2600Nano/tree/strict_input
Remember to use the .XML in the root of the branch.
Maybe you find a minute to check...

**Comment by venice1200** [comment]
Moin!

I compiled the latest "strict" Version and add the XML file to the card,

Testing results..

**Super Breakout with DS#2 Paddle**, DS2 Analog Mode on (LED on)
DS2 no Left Stick Movement
Trigger 1 is Triangle (X)
Select & Start OK

**Super Breakout with USB#1 Paddle** and Logitech Rumble Pad 2, Mode LED off
Left Stick Movement
Trigger 1 is Button 3 (A)
Select is Button 7 (L2), Start is Button 8 (R2)

**2 Button Hero with DS#2 Joystick** and DS2 Analog Mode off or on
Movement with D-Pad
Trigger 1 is Circle (A)
Trigger 2 is Cross (B)
Select & Start OK

**2 Button Hero with USB#1 Joystick**
Mode LED off: Movement with left Stick
Mode LED on: Movement with D-Pad
Trigger 1 = Button 1 (Y)
Trigger 2 = Button 2 (B)
Select is Button 7 (L2), Start is Button 8 (R2)

**Hero with Retro9**
Button 1+2 OK
Movement OK

My Reference is
![Controller](https://github.com/user-attachments/assets/1f74e318-71f9-45db-aa26-e6f0cfe16737)

**Comment by vossstef** [comment]
@venice1200 thanks !
it looks that in principle ok but Trigger mixed up in between USB and DS2...

**Comment by venice1200** [comment]
...and also mixed triggers between joystick and paddle mode.

Any idea why the DS2 left stick has no function since "strict branch" as it was already working in Paddle Games.
Maybe something wrong with the XML?

Many Thanks for your really cool cores!

**Comment by vossstef** [comment]
@venice1200 
got simulation environment running and i just pushed changes into the branch for automatic configuration of the D2 via OSD control. Paddle mode of the DS2 is now automatically set and locked!!! if a port is set to paddle mode. Reverted if port is set to digital mode.

I checked :
Super Breakout with DS#2 Paddle, DS2 Analog Mode on (LED on)

DS2 stick movement for analog control is working as before but you have to press once (activate) one of the dedicated paddle trigger keys X or Y . The core is presently only switching to paddle mode if one of the dedicated paddle keys is pressed.

There are two Keys dedicated to digital Triggers A + B and two dedicated keys for paddle analog trigger (of course only single Trigger per paddle. The Stick is serving as 1st X direction and 2nd paddle Y direction. Therfore the two keys.

Let me try to figure out if the nasty activation press can be removed.

**Comment by venice1200** [comment]
As far as I know, if the pad is not in analog mode, the sticks have no function at all.

**Comment by vossstef** [comment]
> As far as I know, if the pad is not in analog mode, the sticks have no function at all.
will at least fix now that Rumblepad Keys are identical to DS2...

Think Dualshock2: Set ReplyProtocol command 
https://psx-spx.consoledev.net/controllersandmemorycards/#controllers-analog-buttons-dualshock2
should allow to use Dpad and Sticks at the same time. analog XY data need to be converted into digital position with thresholds like in the µC fw. maybe i will find time to try out.

**Comment by venice1200** [comment]
Found this, but Config Mode?!

**Config Mode** - Command 42h "B" - Read Buttons AND analog inputs

Same as command 42h in normal mode, but with forced analog response (ie. analog inputs and L3/R3 buttons are returned **even in Digital Mode with LED=Off**).

**Comment by venice1200** [comment]
Hi @vossstef,
building the latest version, haven't chnaged the XML on the card.

HERO 2 Button
Immedialtly after starting HERO with DS#2 active the Analog Mode LED switched to on.
D-PAD works as expected, buttons OK (Circle & Cross), no Left Stick Movement.

Breakout still don't work for me.
DS#2 Paddle doesn't activate the Analog Mode. Start & Select working.



But if I switched Pad 2 in the Menu to Mouse the Analog Mode was activated!?

**Comment by vossstef** [comment]
@venice1200 XML can stay as before in this special branch. 
I need over they day try to reproduce your findings.

**Comment by venice1200** [comment]
No Hurry 😄

**Comment by vossstef** [comment]
@venice1200 i pushed corrections for TN20k and TM138k Pro.
USB Rumblepad keys are also fixed and shall be identical to DS2 now.

In order to find the problems had to use my 138k Pro where two DS2 Interfaces are wired... Hope my cable arriges over the next days to upgrade my misteryshield.

Pls. let me know how the updates do...

Big thanks already! 
Think this will improve the core significantly and many small glitches in the input control fixed.

It's likely an interim state until i get DPad and left stick in digital mode to work at the same time but for that i will need more time.

**Comment by venice1200** [comment]
Touchdown.

Super Breakout:
DS2 Analog Mode is correctly activated by choosing DS#2 Paddle as Joystick.
Movement using Left DS2 Analog Stick works fine.
Trigger 1 is Triangle/X
Rumblepad:
Buttons 9 & 10 for Select and Start, Trigger 1 is Button 4/X, Movement Ok.

2 Button Hero:
Rumblepad and DS2 Buttons are both using now Buttons A&B as Trigger Buttons.
Movement with DS2 uses the D-Pad.
Movement with Rumblepad can be switched from Left Stick (Mode LED off) to D-Pad (Mode LED on).
Select and Start are Ok.

Retro Stick not tested.

Side-Effect:
If you switch through the Joystick modes the game is restarted if DS#2 Paddle is chosen.

Great Work!

**Comment by vossstef** [comment]
A big  thanks for all the effort in teting!

**Comment by venice1200** [comment]
You are welcome 😄 

Some Ideas!
What do you think about a button configuration on SD?

A file were you can override the default setup and choose your preferred buttons for the Triggers.
I personally prefer the DS2 Buttons
Cross as Trigger 1
Square as Trigger 2

And please, if possible, add some keyboard keys for:
switching the difficulties
swap paddle direction

**Comment by vossstef** [comment]
@venice1200 i had to add a fix for USB Gamepads/ Joystick (Button) and also fixed the game restart if DS# Paddle is selected.

**Comment by venice1200** [comment]
Testing now...

**Comment by venice1200** [comment]
Works fine as expected, no issues found.
Game restart via DS# Paddle is gone.

All the best for '25 🚀

**Comment by vossstef** [comment]
> Happy New Year 🚀 
Also a happy New year!
sorry didn't found time to look  into the ds  topic further yet.

**Comment by vossstef** [comment]
@venice1200 did you designed the PCBA in KiCAD ?
If so could you pls. share the symbol + footprint for the DS2 connector. Thx !

**Comment by venice1200** [comment]
Hi @vossstef,
if everything is Ok with the breakout, i am still waiting for the PCBs, I would add the KiCad Project to the Adapter Documentation.

**Comment by vossstef** [comment]
@venice1200 i just need for larger CAD design the DS2 connector and wondering where to find this very special connector footprint...

**Comment by venice1200** [comment]
I got the base connector layout from the MiSTers PSX Snac Adapter from here

https://github.com/blue212/SNAC-PSX/tree/main

I modified it a bit (changed numbering order and margins) for my needs.

I can upload my data not before Friday as i am not at home.
But the PCBs have arrived germany and I think i can get them before weekend.
And if the footprint matches i can upload my tiny project.

**Comment by venice1200** [comment]
Hi, Adapter is built and successful tested.
![mistery_shield_ds2_adapter_build](https://github.com/user-attachments/assets/68b008e3-89b9-43e1-bccf-4a6837202d05)

I uploaded gerber and kicad files and opened an PR.

The only problem is if you connect the connection cable to a normal pinheader.
It works but there is not enough space. Means a 90 degrees pin header is better.

![IMG_1611](https://github.com/user-attachments/assets/4ba19fce-ad37-47a0-b5a5-d67f700d2d79)


If you like I can provide you and Till with PCB's and PS2 Connectors.

**Comment by vossstef** [comment]
Hi @venice1200 , looks great and will merge now. 
Many thanks !
I will reuse your DS2 foorprint to another PCBA design.
Your documentation will also re-use for the c64 core if you don't mind.

**Comment by venice1200** [comment]
Hi @vossstef 

> I will reuse your DS2 foorprint to another PCBA design.

The Pin footprint is Ok, but I think my "connector footprint" is a bit too small.

> Your documentation will also re-use for the c64 core if you don't mind.

No Problem!

Cheers

**Comment by vossstef** [comment]
Hi @venice1200, i rearranged into a dedicated folder as there is another larger PCBA board coming in the future...
pls. create a pull if you want to change / correct something.
Thx !

**Comment by venice1200** [comment]
Is the planned board for the Tang Nano?

**Comment by vossstef** [comment]
> Is the planned board for the Tang Nano?

It will be a TN20k carrier for Pi Pico WLAN and include in addition a 5 port USB HUB and DS2 connector pads when MIDI i/o not needed.

**Comment by vossstef** [comment]
@venice1200 do you have a bit of time for testing and give feedback for updated core and firmware? thx

**Comment by venice1200** [comment]
So far...

Tang Nano 20k
Companion 1.3.1
Atari 2600 v1.8

No XML file on SD Card
Mini 4x3 Keyboard (re-programmed) is working well.

With BL616 
JOY#1 = USB#1 (Logitech Rumblepad 2)
 HERO works fine in both Modes (Analog/Digital)
 HERO (2Button Version) works fine in both Modes (Analog/Digital)
 Super Breakout works fine with Analog Joysticks (DS2/USB) *
JOY#1 = DS2#2
 HERO works fine
 HERO (2Button Version) works fine
 Super Breakout works fine with Analog Joysticks (DS2/USB) *
 
With MiSTeryShield20k
JOY#1 = DS2#2
 HERO works fine
 HERO (2Button Version) works fine.
 Super Breakout works fine with Analog Joysticks (DS2/USB) *

Notes
* Super Breakout works but one version has the picture streched horizontally so you can't see the players pad.

![Image](https://github.com/user-attachments/assets/9bd9e32e-d029-4119-a94f-dc899060d9a7)

Another Super Breakout Version look correct, Strange.

![Image](https://github.com/user-attachments/assets/f637f1ef-edf5-465b-9b39-83011ff59106)

More to come...

**Comment by vossstef** [comment]
@venice1200 many thanks !

Some Games are not working due to video issues that even the7800 stabilizer can't correct properly.

In the original  Mist / MISTer A2600 original core there was no video stabilizer at all and only very few games had been working. Situation now should be somehow ok and identical level than A7800  running 2600 games.
